# for quaternion, we use the format [x, y, z, w]
cam1:
  height: 270
  width: 480
  distortion_model: plumb_bob
  d:
    - -0.05571987107396126
    - 0.06888450682163239
    - -0.0009926625061780214
    - 0.0002807408745866269
    - -0.021903323009610176
  k:
    - 239.0280303955078
    - 0.0
    - 238.82595825195312
    - 0.0
    - 238.77781677246094
    - 133.7902069091797
    - 0.0
    - 0.0
    - 1.0
  t:
    - 0.50
    - 0.49
    - 0.638426
  q:
    - -0.013
    - 0.946
    - -0.323
    - 0.032


cam2:
  height: 270
  width: 480
  distortion_model: plumb_bob
  d:
    - -0.05574629828333855
    - 0.06564962863922119
    - 0.0002993989910464734
    - 0.0007119299843907356
    - -0.021328549832105637
  k:
    - 241.43362426757812
    - 0.0
    - 241.46742248535156
    - 0.0
    - 241.1495361328125
    - 135.84083557128906
    - 0.0
    - 0.0
    - 1.0
  t:
    - 0.56
    - -0.51
    - 0.682
  q:
    - 0.958
    - 0.005
    - -0.014
    - -0.286


cam3:
  height: 270
  width: 480
  distortion_model: plumb_bob
  d:
    - -0.05411041900515556
    - 0.06525939702987671
    - -0.00017920040409080684
    - 0.00034587684785947204
    - -0.02144884504377842
  k:
    - 241.9549102783203
    - 0.0
    - 241.23287963867188
    - 0.0
    - 241.7293701171875
    - 137.0078125
    - 0.0
    - 0.0
    - 1.0
  t:
    - 1.260047
    - -0.01
    - 0.605
  q:
    - 0.629
    - 0.625
    - -0.318
    - -0.336