R_transform:
- - 0.6689656395053947
  - -0.7244732163449712
  - 0.1662032850454842
- - 0.14671435909834582
  - 0.3479046865981714
  - 0.9259790634120134
- - -0.728669932133541
  - -0.5950637678785363
  - 0.3390269047770393
description: Rotation from HAMER hand frame to table-aligned frame (X=forward, Y=left,
  Z=down)
quat_transform:
- -0.4954881552898576
- 0.29150992363714523
- 0.2837941942118765
- 0.7674466155506529
